### PR TITLE
upload_response.html.erb typo fix

### PR DESCRIPTION
**Pull request by benrfairless**
Created pending https://github.com/mysociety/alaveteli/pull/1543 merge into Master upstream

### CODE REVIEW

**Comment by henare** [comment]
Once you're happy this is working in staging @brfairless I'll merge and deploy.

**Comment by henare** [comment]
I'm confused. Is this ready to go now?

Let's only merge things into the `production` branch when they're about to be deployed, and by the person that is deploying them. We're now in the situation that what is currently deployed to production is out of sync with what's in our production branch. This is confusing and dangerous.

**Comment by benrfairless** [comment]
Whoops! Good point. Can you deploy please? :)

**Comment by henare** [comment]
This is **so confusing** :( There are 9 commits in this pull request when only 3 are remotely relevant to this topic.

I'm very tempted to revert this but since it's already been merged into the production branch I don't feel confident doing that either.

Please do not push to the `production` or `staging` branches in the future.

**Pull request merged**
