### PR TITLE
Email Disclaimer Changes (#352)

### PR DESCRIPTION
**Pull request by benrfairless**
My suggested fix of #352 

I've made the email signature read like this:

<b> Initial Request </b>

<i>Please use this email address for all replies to this request: [FOI Request Email]@righttoknow.org.au
This email address satisfies s.15(2)(c) of the Freedom of Information Act.

<i>Is [FOI Contact Address] the wrong address for Freedom of Information requests to Right to Know? If so, please contact us using this form: http://test.righttoknow.org.au/change_request/new?body=rtk

<i>Disclaimer: The views expressed in this request are those of the sender, and are not endorsed by Right to Know or the OpenAustralia Foundation.

<i>This message and any reply that you make will be published on the internet. More Information can be found at http://test.righttoknow.org.au/help/officers</i>

<b> Follow-Up Messages </b>

<i>Please use this email address for all replies to this request: [FOI Request Email]@righttoknow.org.au

<i>Disclaimer: The views expressed in this request are those of the sender, and are not endorsed by Right to Know or the OpenAustralia Foundation.

<i>This message and any reply that you make will be published on the internet. More Information can be found at http://test.righttoknow.org.au/help/officers

### CODE REVIEW

**Comment by henare** [comment]
This PR you've proposed isn't just about reducing the size. You've got two significant changes in there.

That's different to #352.

**Comment by benrfairless** [comment]
Touché @henare. The main changes are the removal of content that has been there since (I guess) RTKs creation.

What are your thoughts on the proposed changes?

**Comment by henare** [comment]
I think it's important to leave the PDF thing in and I'm not sure about the inclusion of the new disclaimer :-/

**Comment by benrfairless** [comment]
On the Disclaimer, I'm happy to take that out (I was looking at an email between WDTK and Rother District Council when I wrote it, and I thought it was important to have there as technically you can say <i> anything </i> via our site).

Can I ask what benefit you see in the PDF thing? PDF seems to have become a "standard" for sending Government data to RTK (I suspect in part because its a PITA to copy and paste, and its easy to run off a printer) and I don't think the PDF note is doing much I'm afraid :(

**Pull request closed without merging**
