### PR TITLE
Make the form input-label layout vertical i.e. labels above inputs.

### LINKED ISSUE #523: move to vertical form design
In our theme we override the default form design of labels stacked on top of form inputs:

[Right To Know](https://www.righttoknow.org.au/new/sydney_catchment_authority):
screen shot 2015-04-24 at 9 46 29 am

[Alaveteli Demo](http://demo.alaveteli.org/new/dfh):
screen shot 2015-04-24 at 9 44 08 am

I don't think this helps the user in any clear way and makes our theme more complex.

Scanning the labels vertically breaks up the flow of the page and distracts from the immediate task at hand: writing a summary of your request.

### PR DESCRIPTION
**Pull request by equivalentideas**
This moves form labels above their inputs rather than next to them, as is the current layout in most places. This removes Right To Know overrides of the default alaveteli layout for forms, reducing the complexity of our theme. I think it is also a win for users in simplifying these forms.

Closes #523 

Here's some notes of form label placement from [Luke Wroblewski](http://www.lukew.com/ff/entry.asp?504):

> Top-aligned labels tend to reduce completion times (how long it takes to complete a form) the most for familiar data (i.e. address, credit card, etc.) because they only require a single eye fixation to take in both input label & field. Top-aligned labels also work well for forms that require localization or long labels as there is plenty of horizontal real estate to expand/contract the label without negatively impacting the overall page layout. Top-aligned labels, however, do take up a lot of vertical real estate.
> 
> Left-aligned forms are the slowest of the three to complete because of the number of eye fixations they require to parse. However, for forms with lots of optional fields or unfamiliar data (like preferences dialogs or advanced settings), they allow users to effectively scan labels. In fact, if you want users to slow down and consider each input in a form more carefully, left-aligned labels are a good way to go.

You can see why Alaveteli went for a 'Top-aligned' pattern with the needs for localization, and the general push for simplicity.

I've tested this out around the site, but it's quite a major layout change and it would be good if you could take some of the forms for a quick test spin @henare .
## Before:

screen shot 2015-04-27 at 2 02 10 pm
screen shot 2015-04-27 at 2 03 57 pm
screen shot 2015-04-27 at 2 04 16 pm
screen shot 2015-04-27 at 2 19 14 pm
## After:

screen shot 2015-04-27 at 2 19 27 pm
screen shot 2015-04-27 at 2 04 35 pm
screen shot 2015-04-27 at 2 02 57 pm
screen shot 2015-04-27 at 2 02 34 pm
screen shot 2015-04-27 at 2 01 59 pm

### CODE REVIEW

**Comment by henare** [comment]
If there are errors on a form there's little pink bars below some fields that don't look like they should be there.

**Comment by equivalentideas** [comment]
> If there are errors on a form there's little pink bars below some fields that don't look like they should be there.

Here's what that looks like:
screen shot 2015-04-27 at 4 18 24 pm
screen shot 2015-04-27 at 4 18 36 pm

**Comment by henare** [comment]
I haven't found any other issues. Once that's fixed we can merge.

**Comment by equivalentideas** [comment]
> If there are errors on a form there's little pink bars below some fields that don't look like they should be there.

I think we should remove the red background colour and use the in-build erroring field style in Alaveteli, just the red border.

I'll make that commit and push it here.

**Comment by equivalentideas** [comment]
After 23d262e the erroring forms look like:

screen shot 2015-04-27 at 4 33 20 pm
screen shot 2015-04-27 at 4 33 30 pm

**Pull request merged**
