### PR TITLE
added some links and an example

### PR DESCRIPTION
**Pull request by equivalentideas**
To help people without a lot of url encoding experience (me :P ).

Hope this is useful, it's a bit of a long example, but just one I had on hand.

### CODE REVIEW

**Comment by henare** [comment]
Great idea Luke :thumbsup: 

Can you change your links to use Rails' `link_to` helper?

**Comment by equivalentideas** [comment]
Hey Henare, I'll give it a go.

Could you explain why you want them in this format? Just trying to learn.

**Comment by henare** [comment]
Cool. It's more concise and more Rails-like to use the helper.

**Comment by equivalentideas** [comment]
I've just submited a new pull request for this with the links written in rails.

**Comment by henare** [comment]
Closing this - @equivalentideas has opened #6 instead.

**Pull request closed without merging**
