### PR TITLE
Minor modification for links

### PR DESCRIPTION
**Pull request by powerwlsl**
Add target blank to some of link tags on the footer so that it opens in a new tab.

### CODE REVIEW

**Comment by powerwlsl** [comment]
@equivalentideas I just did some minor changes on link tags.

**Comment by equivalentideas** [comment]
> @equivalentideas I just did some minor changes on link tags.

Thanks @powerwlsl . Is this in response to a specific Issue?

**Comment by powerwlsl** [comment]
Oh I didn't know I have to fix something that has specific issue. :) !

**Comment by equivalentideas** [comment]
@powerwlsl you don't necessarily, but we generally open issues for any change we want to make so we can discuss it :)

The issues are a good place to look to start contributing because that lists all the stuff we already know we want to change :D Thanks for you interest in contributing!

**Pull request closed without merging**
