### PR TITLE
Remove outgoing footer customisations

### LINKED ISSUE #410: Update outgoing mail footer so it makes sense when ACT is covered
@brfairless had a first go in #408.

### PR DESCRIPTION
**Pull request by henare**
Our two customisations were asking FOI officers to not use PDF and
reminding them that requests from RTK are valid and even the
Information Commissioner has said so.

I'm suggesting we remove them since they're not having an impact.

The PDF one obviously isn't since we're still getting plenty of PDFs
and the valid request one has still seen instances of departments
playing silly buggers.

One technique that has been more effective is writing these statements
in the body of the message or in follow up messages. So let's continue
to do that where there's a problem but not codify it in the system.

Removing this reverts it to the standard Alaveteli template, which looks like this example request:

> Dear Capital Linen Service,
> 
> This is a test, please ignore it.
> 
> Yours faithfully,
> 
> Tester
> ---
> 
> Please use this email address for all replies to this request:
> request-10-51afc4aa@localhost
> 
> Is test@example.com the wrong address for Freedom of Information requests to Capital Linen Service? If so, please contact us using this form:
> https://localhost:3000/change_request/new?body=capital_linen_service
> 
> Disclaimer: This message and any reply that you make will be published on the internet. Our privacy and copyright policies:
> https://localhost:3000/help/officers
> 
> If you find this service useful as an FOI officer, please ask your web manager to link to us from your organisation's FOI page.
> ---

Closes #410.

### CODE REVIEW

**Comment by henare** [comment]
You could argue this is controversial. I'm interested in your thoughts @mlandauer and @brfairless.

**Comment by benrfairless** [comment]
So would the help file be there if an authority is wondering "who the hell is Right to Know, and why are they sending me so many requests?!". I think particularly for authorities which might not have dealt with a request using our service it could be helpful to say "this request is made by a user of RTK, not RTK" and perhaps something about encouraging officers to get in touch with us if they don't understand what's going on?

**Comment by henare** [comment]
@brfairless I should've included an example of what the messages look like when removing this customisation. I've now done that in the PR description above.

> So would the help file be there if an authority is wondering "who the hell is Right to Know, and why are they sending me so many requests?!". I think particularly for authorities which might not have dealt with a request using our service it could be helpful to say "this request is made by a user of RTK, not RTK" and perhaps something about encouraging officers to get in touch with us if they don't understand what's going on?

This wasn't addressed directly in our customisations before either. Unless you're talking about the disclaimer line, which is still included in the default Alaveteli template.

**Comment by benrfairless** [comment]
> This wasn't addressed directly in our customisations before either.

Having the chance to read it, I don't like linking the Officer help page with "privacy and copyright policies" like the current one does. I know at least in my home state there are agencies which have never been subjected to FOI requests before, and we should try to do the right thing for the agency, as the agency is also a user of the service (by replying to requests).

For example, this sounds nicer then what the default is:

> This request has been made by an individual using Right to Know. You can reply to this email like any other to respond to this request. More information on how Right to Know works can be found at https://localhost:3000/help/officers

On the PDF thing, I wanted to remove it for the reasons you specified, but @mlandauer wanted it to remain. I don't think agencies care about accessibility unless you say "I'm blind, help me" which is quite rude if I can say so....

**Comment by henare** [comment]
I really like your change @brfairless. Let's wait to hear some other thoughts too.

**Comment by henare** [comment]
I've largely used @brfairless' suggestion for customising the disclaimer to make it more friendly.

I've also included the bit from Alaveteli where we specifically say that responses will be published on the internet because I think it's good to be up front about that.

Since there's been no other feedback I'm going to go ahead and merge this.

**Pull request merged**
