### PR TITLE
Update Email Footer

### PR DESCRIPTION
**Pull request by benrfairless**
Update email footer to provide link to OAIC decision on s.15(2)(c).

### CODE REVIEW

**Comment by henare** [comment]
Can we make this more concise by shortening the URL and removing the repetition of the section of the act?

**Comment by benrfairless** [comment]
I've made a few changes which shorten the URL and upload the letter to RTK.

The signature now says:

> The Freedom of Information Commissioner has recommended that agencies accept requests from Right to Know as valid for the purpose of s.15(2)(c) of the Freedom of Information Act. See https://www.righttoknow.org.au/assets/OAIC-Letter.pdf for details of the OAIC decision.

**Comment by benrfairless** [comment]
Does it look OK now @henare? I've tested it in vagrant and it works OK for me.

**Comment by henare** [comment]
Nice!

**Comment by henare** [comment]
Deployed.

**Pull request merged**
