### PR TITLE
Upgrade to 0.16

### LINKED ISSUE #310: Update theme to be compatible with Alaveteli 0.16
https://github.com/mysociety/alaveteli/blob/release/0.16/doc/THEME-ASSETS-UPGRADE.md

### PR DESCRIPTION
**Pull request by henare**
This is a copy of @brfairless's #325 PR but it targets the `production` branch. It fixes #310 and is currently deployed to staging.

Note you need to add `RAILS_ENV` to your Capistrano config (see https://github.com/mysociety/alaveteli/issues/1436).

### CODE REVIEW

**Comment by benrfairless** [comment]
I'm not sure if #327 would be introduced if we deployed this. Further investigation needed I think.

**Comment by henare** [comment]
:+1:

**Comment by benrfairless** [comment]
#327  appears to only be affecting Mac Mail (issue raised upstream - https://github.com/mysociety/alaveteli/issues/1437)

I would suggest this is OK to go, I doubt there are any Govt departments using Mac Mail and if they are we can always make the attachments available manually.

**Comment by henare** [comment]
I've upgraded staging to 0.17.

I'll deploy that to production first thing tomorrow. I've decided it's best I'm alert and available right after I do the deploy rather than have it quietly run all night.

**Comment by henare** [comment]
:shipit: Deployed :rocket: :sparkles:

**Pull request merged**
