### PR TITLE
#384 - Add contact@righttoknow recipients to contact page

### LINKED ISSUE #384: Provide information on who is on the contact list
On the OAF website (https://www.openaustraliafoundation.org.au/contact-us/who-do-the-emails-go-to/) we list the names of the people who receive emails sent to contact@oaf

Should we do the same for Right to Know?

### PR DESCRIPTION
**Pull request by benrfairless**
fixes #384

Adding everyone to the contact page. Can you check that you're happy with the wording, I'll need to test it tonight (don't have my laptop with me at the moment).

### CODE REVIEW

**Comment by henare** [comment]
Woo :tada: 

> Can you check that you're happy with the wording

Wording looks really good to me.

> I'll need to test it tonight (don't have my laptop with me at the moment).

Ping me again when this is ready for merge.

**Comment by equivalentideas** [comment]
Love the 'that's transparency!' :guitar:

**Comment by henare** [comment]
@kat came up with that when she created the original page on the OAF site :sparkling_heart:

**Comment by benrfairless** [comment]
Thanks @kat, yeah it was a blatant copy/paste from OAF.org.au. Hopefully it won't increase the spam haha.

**Comment by henare** [comment]
Blatant copy/paste is good :flags:

**Comment by benrfairless** [comment]
This is what it looks like now:

**Comment by benrfairless** [comment]
@henare if you're happy, its all yours to deploy :rocket:

**Comment by henare** [comment]
Great stuff :dolphin: Thanks @brfairless!

**Pull request merged**
