### PR TITLE
Theme updates to upgrade to 0.16 - #310

### LINKED ISSUE #310: Update theme to be compatible with Alaveteli 0.16
https://github.com/mysociety/alaveteli/blob/release/0.16/doc/THEME-ASSETS-UPGRADE.md

### PR DESCRIPTION
**Pull request by benrfairless**
Can someone peer review this please. It should (hopefully) fix #310

### CODE REVIEW

**Comment by henare** [comment]
Hey Ben, do you have a development environment set up? Most pages I've tested work but some obvious ones don't (like the home page).

I'll be happy to help you get set up if you don't have an environment.

**Comment by benrfairless** [comment]
hey @henare I've not got any of that stuff setup. Perhaps this is a conversation to take to Email/Chat?

**Comment by henare** [comment]
Gladly! You've got my email or IM: henare.degan@gmail.com

**Comment by benrfairless** [comment]
Closing this. I'll re-raise when I've got my act together and sorted out the issues.

**Pull request closed without merging**
